# Generated by Django 5.1.2 on 2024-10-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nome',
        ),
    ]
